# permissions for end users to view cloudflaretunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudflaretunnel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflaretunnel-viewer-role
rules:
- apiGroups:
  - apps.ar2ro.io
  resources:
  - cloudflaretunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.ar2ro.io
  resources:
  - cloudflaretunnels/status
  verbs:
  - get
