/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package apps

import (
	v1alpha1apps "github.com/arturoguerra/cloudflare-tunnel-operator/apis/apps/v1alpha1"
	v1alpha1cloudflaretunnel "github.com/arturoguerra/cloudflare-tunnel-operator/apis/apps/v1alpha1/cloudflared"
)

// Code generated by operator-builder. DO NOT EDIT.

// CloudflareTunnelLatestGroupVersion returns the latest group version object associated with this
// particular kind.
var CloudflareTunnelLatestGroupVersion = v1alpha1apps.GroupVersion

// CloudflareTunnelLatestSample returns the latest sample manifest associated with this
// particular kind.
var CloudflareTunnelLatestSample = v1alpha1cloudflaretunnel.Sample(false)
