apiVersion: apps.ar2ro.io/v1alpha1
kind: CloudflareTunnel
metadata:
  name: cloudflaretunnel-sample
spec:
  namespace: "Namespace of target service"
  replicas: 1
  tunnelID: "Cloudflare Tunnel ID"
  service:
    protocol: "http | https | tcp | ssh | tls+tcp"
    name: "Service Name"
    port: 443
  tunnelCredentials: "base64 of tunnel.json"
