apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-auth
  namespace: cloudflared # +operator-builder:field:name=namespace,type=string
type: Opaque
data:
  # +operator-builder:field:name=tunnelCredentials,type=string,replace="tunnelcredentials"
  tunnel.json: |
    tunnelcredentials